baseURL = "https://kiyubits.github.io/kiyubytes"
languageCode = "en-us"
title = "Kiyubytes"
theme = "gokarna"
enableRobotsTXT = true
[params]
  description = "Documenting some of my physics and coding adventures"
  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-m"
  accentColor = "#08F"
  showPostsOnHomePage = "recent"
  footer = "Kiyubits"
  togglePreviousAndNextButtons = "true"
[Author]
  name = "Kiyubits"
[menu]
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    pre = ""
    post = ""
    name = "Posts"
    weight = 1
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/kiyubits"
    weight = 3
    pre = "<span data-feather='github'></span>"
  
